using FaceUPAI.Controllers.Common;
using FaceUPAI.DataAccessService;
using FaceUPAI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlTypes;

namespace FaceUPAI.API
{
	public class FeedAPI : ControllerBase
	{
	public IActionResult Index()
	{
	return View();
	}
	private IActionResult View()
	{
	throw new NotImplementedException();
	}
		/// <summary>
		/// Saves a record to the Feed table.
		/// </summary>
	[HttpPost]
        [EnableCors("AllowAll")]
        [Route("FeedInsert")]
		public  IActionResult FeedInsert([FromBody] Feed feed)
		{
			return ApiHandler.Handle(() =>
	{

			SqlParameter[] parameters = new SqlParameter[]
			{
				new SqlParameter("@TenantID", feed.TenantID == 0 ? SqlInt32.Null : feed.TenantID ),
				new SqlParameter("@UserID", feed.UserID == 0 ? SqlInt32.Null : feed.UserID ),
				new SqlParameter("@Title", feed.Title),
				new SqlParameter("@Description", feed.Description),
				new SqlParameter("@MediaType", feed.MediaType),
				new SqlParameter("@PostType", feed.PostType),
				new SqlParameter("@MediaURL", feed.MediaURL),
				new SqlParameter("@ThumbnailURL", feed.ThumbnailURL),
				new SqlParameter("@Duration", feed.Duration == 0 ? SqlInt32.Null : feed.Duration ),
				new SqlParameter("@DisplayOrder", feed.DisplayOrder == 0 ? SqlInt32.Null : feed.DisplayOrder ),
				new SqlParameter("@PublishDate", feed.PublishDate == DateTime.MinValue ? SqlDateTime.Null : feed.PublishDate ),
				new SqlParameter("@IsActive", feed.IsActive),
				new SqlParameter("@IsDeleted", feed.IsDeleted),
				new SqlParameter("@IsAdminPost", feed.IsAdminPost),
				new SqlParameter("@DateAdded", feed.DateAdded == DateTime.MinValue ? SqlDateTime.Null : feed.DateAdded ),
				new SqlParameter("@DateModified", feed.DateModified == DateTime.MinValue ? SqlDateTime.Null : feed.DateModified ),
				new SqlParameter("@UpdatedByUser", feed.UpdatedByUser),
				new SqlParameter("@SourceTable", feed.SourceTable),
				new SqlParameter("@SourceID", feed.SourceID == 0 ? SqlInt32.Null : feed.SourceID ),
				new SqlParameter("@UserName", feed.UserName),
				new SqlParameter("@UserPhoto", feed.UserPhoto),
				new SqlParameter("@FeedCategory", feed.FeedCategory),
				new SqlParameter("@Location", feed.Location),
				new SqlParameter("@Amount", feed.Amount),
				new SqlParameter("@IsAutoGenerated", feed.IsAutoGenerated)
			};

			feed.FeedID = Convert.ToInt32(DataAccess.ExecuteScalar(CommandType.StoredProcedure, "FeedInsert", parameters));
			return Ok(new {FeedID=feed.FeedID});
			}, this);
		}

		/// <summary>
		/// Updates a record in the Feed table.
		/// </summary>
	[HttpPost]
        [EnableCors("AllowAll")]
        [Route("FeedUpdate")]
		public  IActionResult FeedUpdate([FromBody] Feed feed)
		{
			return ApiHandler.Handle(() =>
	{

			SqlParameter[] parameters = new SqlParameter[]
			{
				new SqlParameter("@FeedID", feed.FeedID == 0 ? SqlInt32.Null : feed.FeedID ),
				new SqlParameter("@TenantID", feed.TenantID == 0 ? SqlInt32.Null : feed.TenantID ),
				new SqlParameter("@UserID", feed.UserID == 0 ? SqlInt32.Null : feed.UserID ),
				new SqlParameter("@Title", feed.Title),
				new SqlParameter("@Description", feed.Description),
				new SqlParameter("@MediaType", feed.MediaType),
				new SqlParameter("@PostType", feed.PostType),
				new SqlParameter("@MediaURL", feed.MediaURL),
				new SqlParameter("@ThumbnailURL", feed.ThumbnailURL),
				new SqlParameter("@Duration", feed.Duration == 0 ? SqlInt32.Null : feed.Duration ),
				new SqlParameter("@DisplayOrder", feed.DisplayOrder == 0 ? SqlInt32.Null : feed.DisplayOrder ),
				new SqlParameter("@PublishDate", feed.PublishDate == DateTime.MinValue ? SqlDateTime.Null : feed.PublishDate ),
				new SqlParameter("@IsActive", feed.IsActive),
				new SqlParameter("@IsDeleted", feed.IsDeleted),
				new SqlParameter("@IsAdminPost", feed.IsAdminPost),
				new SqlParameter("@DateAdded", feed.DateAdded == DateTime.MinValue ? SqlDateTime.Null : feed.DateAdded ),
				new SqlParameter("@DateModified", feed.DateModified == DateTime.MinValue ? SqlDateTime.Null : feed.DateModified ),
				new SqlParameter("@UpdatedByUser", feed.UpdatedByUser),
				new SqlParameter("@SourceTable", feed.SourceTable),
				new SqlParameter("@SourceID", feed.SourceID == 0 ? SqlInt32.Null : feed.SourceID ),
				new SqlParameter("@UserName", feed.UserName),
				new SqlParameter("@UserPhoto", feed.UserPhoto),
				new SqlParameter("@FeedCategory", feed.FeedCategory),
				new SqlParameter("@Location", feed.Location),
				new SqlParameter("@Amount", feed.Amount),
				new SqlParameter("@IsAutoGenerated", feed.IsAutoGenerated)
			};

			 var FeedID = Convert.ToInt32(DataAccess.ExecuteNonQuery(CommandType.StoredProcedure, "FeedUpdate", parameters));
			return Ok(new {FeedID =FeedID});
			}, this);
		}

		/// <summary>
		/// Deletes a record from the Feed table by its primary key.
		/// </summary>
	[HttpPost]
        [EnableCors("AllowAll")]
        [Route("FeedDelete")]
		public  IActionResult FeedDelete(int feedID, int tenantID)
		{
			return ApiHandler.Handle(() =>
	{
			SqlParameter[] parameters = new SqlParameter[]
			{
				new SqlParameter("@FeedID", feedID)

				,new SqlParameter("@TenantID", tenantID)			};

			 var feedDeletedID = Convert.ToInt32(DataAccess.ExecuteScalar(CommandType.StoredProcedure, "FeedDelete", parameters));
			return Ok(new {FeedID =feedDeletedID});
			}, this);
		}

		/// <summary>
		/// Selects a single record from the Feed table.
		/// </summary>
	[HttpPost]
        [EnableCors("AllowAll")]
        [Route("FeedSelect")]
		public IActionResult FeedSelect(int feedID,int tenantID)
		{
			return ApiHandler.Handle(() =>
	{
			SqlParameter[] parameters = new SqlParameter[]
			{
				new SqlParameter("@FeedID", feedID)
,				new SqlParameter("@TenantID", tenantID)
			};

			using (SqlDataReader dataReader = DataAccess.ExecuteReader(CommandType.StoredProcedure, "FeedSelect", parameters))
			{
				List<Feed> FeedList = new List<Feed>();
				while (dataReader.Read())
				{
					Feed Feed = MakeFeed(dataReader);
					FeedList.Add(Feed);
				}

				return  Ok(new {FeedList});
			}
			}, this);
		}

		/// <summary>
		/// Selects a single record from the Feed table.
		/// </summary>
	[HttpPost]
        [EnableCors("AllowAll")]
        [Route("FeedSelectAll")]
		public IActionResult FeedSelectAll(int tenantID){
			return ApiHandler.Handle(() =>
	{
			SqlParameter[] parameters = new SqlParameter[]
			{
				new SqlParameter("@TenantID", tenantID)
			};
			using (SqlDataReader dataReader = DataAccess.ExecuteReader(CommandType.StoredProcedure, "FeedSelectAll", parameters))
			{
				List<Feed> FeedList = new List<Feed>();
				while (dataReader.Read())
				{
					Feed Feed = MakeFeed(dataReader);
					FeedList.Add(Feed);
				}

				return  Ok(new {FeedList});
			}
			}, this);
		}

		/// <summary>
		/// Selects all query records from the Feed table by a ak=ll query.
		/// </summary>
	[HttpPost]
        [EnableCors("AllowAll")]
        [Route("FeedSelectByQuery")]
		public  IActionResult FeedSelectByQuery(int tenantID,int schoolID,string Query)
		{
			return ApiHandler.Handle(() =>
	{
			SqlParameter[] parameters = new SqlParameter[]
			{
				new SqlParameter("@TenantID", tenantID),				new SqlParameter("@SchoolID", schoolID),				new SqlParameter("@Query", Query),

			};

			using (SqlDataReader dataReader = DataAccess.ExecuteReader( System.Data.CommandType.StoredProcedure, "FeedSelectByQuery", parameters))
			{
				List<Feed> FeedList = new List<Feed>();
				while (dataReader.Read())
				{
					Feed Feed = MakeFeed(dataReader);
					FeedList.Add(Feed);
				}

				return  Ok(new {FeedList});
			}
			}, this);
		}

		/// <summary>
		/// Creates a new instance of the Feed class and populates it with data from the specified SqlDataReader.
		/// </summary>
		public  Feed MakeFeed(SqlDataReader dataReader)
		{
			Feed feed = new Feed();
			feed.FeedID = DataAccess.GetInt32(dataReader, "FeedID", 0);
			feed.TenantID = DataAccess.GetInt32(dataReader, "TenantID", 0);
			feed.UserID = DataAccess.GetInt32(dataReader, "UserID", 0);
			feed.Title = DataAccess.GetString(dataReader, "Title", String.Empty);
			feed.Description = DataAccess.GetString(dataReader, "Description", String.Empty);
			feed.MediaType = DataAccess.GetString(dataReader, "MediaType", String.Empty);
			feed.PostType = DataAccess.GetString(dataReader, "PostType", String.Empty);
			feed.MediaURL = DataAccess.GetString(dataReader, "MediaURL", String.Empty);
			feed.ThumbnailURL = DataAccess.GetString(dataReader, "ThumbnailURL", String.Empty);
			feed.Duration = DataAccess.GetInt32(dataReader, "Duration", 0);
			feed.DisplayOrder = DataAccess.GetInt32(dataReader, "DisplayOrder", 0);
			feed.PublishDate = DataAccess.GetDateTime(dataReader, "PublishDate", DateTime.MinValue);
			feed.IsActive = DataAccess.GetBoolean(dataReader, "IsActive", false);
			feed.IsDeleted = DataAccess.GetBoolean(dataReader, "IsDeleted", false);
			feed.IsAdminPost = DataAccess.GetBoolean(dataReader, "IsAdminPost", false);
			feed.DateAdded = DataAccess.GetDateTime(dataReader, "DateAdded", DateTime.MinValue);
			feed.DateModified = DataAccess.GetDateTime(dataReader, "DateModified", DateTime.MinValue);
			feed.UpdatedByUser = DataAccess.GetString(dataReader, "UpdatedByUser", String.Empty);
			feed.SourceTable = DataAccess.GetString(dataReader, "SourceTable", String.Empty);
			feed.SourceID = DataAccess.GetInt32(dataReader, "SourceID", 0);
			feed.UserName = DataAccess.GetString(dataReader, "UserName", String.Empty);
			feed.UserPhoto = DataAccess.GetString(dataReader, "UserPhoto", String.Empty);
			feed.FeedCategory = DataAccess.GetString(dataReader, "FeedCategory", String.Empty);
			feed.Location = DataAccess.GetString(dataReader, "Location", String.Empty);
			feed.Amount = DataAccess.GetDecimal(dataReader, "Amount", Decimal.Zero);
			feed.IsAutoGenerated = DataAccess.GetBoolean(dataReader, "IsAutoGenerated", false);

			return feed;
		}

	}
	}
