using System;
namespace FaceUPAI.Models
{
	public class Feed
	{
		#region Fields

		private int feedID;
		private int tenantID;
		private int userID;
		private string title;
		private string description;
		private string mediaType;
		private string postType;
		private string mediaURL;
		private string thumbnailURL;
		private int duration;
		private int displayOrder;
		private DateTime publishDate;
		private bool isActive;
		private bool isDeleted;
		private bool isAdminPost;
		private DateTime dateAdded;
		private DateTime dateModified;
		private string updatedByUser;
		private string sourceTable;
		private int sourceID;
		private string userName;
		private string userPhoto;
		private string feedCategory;
		private string location;
		private decimal amount;
		private bool isAutoGenerated;

		#endregion

		#region Constructors

		/// <summary>
		/// Initializes a new instance of the Feed class.
		/// </summary>
		public Feed()
		{
		}

		/// <summary>
		/// Initializes a new instance of the Feed class.
		/// </summary>
		public Feed(int tenantID, int userID, string title, string description, string mediaType, string postType, string mediaURL, string thumbnailURL, int duration, int displayOrder, DateTime publishDate, bool isActive, bool isDeleted, bool isAdminPost, DateTime dateAdded, DateTime dateModified, string updatedByUser, string sourceTable, int sourceID, string userName, string userPhoto, string feedCategory, string location, decimal amount, bool isAutoGenerated)
		{
			this.tenantID = tenantID;
			this.userID = userID;
			this.title = title;
			this.description = description;
			this.mediaType = mediaType;
			this.postType = postType;
			this.mediaURL = mediaURL;
			this.thumbnailURL = thumbnailURL;
			this.duration = duration;
			this.displayOrder = displayOrder;
			this.publishDate = publishDate;
			this.isActive = isActive;
			this.isDeleted = isDeleted;
			this.isAdminPost = isAdminPost;
			this.dateAdded = dateAdded;
			this.dateModified = dateModified;
			this.updatedByUser = updatedByUser;
			this.sourceTable = sourceTable;
			this.sourceID = sourceID;
			this.userName = userName;
			this.userPhoto = userPhoto;
			this.feedCategory = feedCategory;
			this.location = location;
			this.amount = amount;
			this.isAutoGenerated = isAutoGenerated;
		}

		/// <summary>
		/// Initializes a new instance of the Feed class.
		/// </summary>
		public Feed(int feedID, int tenantID, int userID, string title, string description, string mediaType, string postType, string mediaURL, string thumbnailURL, int duration, int displayOrder, DateTime publishDate, bool isActive, bool isDeleted, bool isAdminPost, DateTime dateAdded, DateTime dateModified, string updatedByUser, string sourceTable, int sourceID, string userName, string userPhoto, string feedCategory, string location, decimal amount, bool isAutoGenerated)
		{
			this.feedID = feedID;
			this.tenantID = tenantID;
			this.userID = userID;
			this.title = title;
			this.description = description;
			this.mediaType = mediaType;
			this.postType = postType;
			this.mediaURL = mediaURL;
			this.thumbnailURL = thumbnailURL;
			this.duration = duration;
			this.displayOrder = displayOrder;
			this.publishDate = publishDate;
			this.isActive = isActive;
			this.isDeleted = isDeleted;
			this.isAdminPost = isAdminPost;
			this.dateAdded = dateAdded;
			this.dateModified = dateModified;
			this.updatedByUser = updatedByUser;
			this.sourceTable = sourceTable;
			this.sourceID = sourceID;
			this.userName = userName;
			this.userPhoto = userPhoto;
			this.feedCategory = feedCategory;
			this.location = location;
			this.amount = amount;
			this.isAutoGenerated = isAutoGenerated;
		}

		#endregion

		#region Properties
		/// <summary>
		/// Gets or sets the FeedID value.
		/// </summary>
		public  int FeedID
		{
			get { return feedID; }
			set { feedID = value; }
		}

		/// <summary>
		/// Gets or sets the TenantID value.
		/// </summary>
		public  int TenantID
		{
			get { return tenantID; }
			set { tenantID = value; }
		}

		/// <summary>
		/// Gets or sets the UserID value.
		/// </summary>
		public  int UserID
		{
			get { return userID; }
			set { userID = value; }
		}

		/// <summary>
		/// Gets or sets the Title value.
		/// </summary>
		public  string Title
		{
			get { return title; }
			set { title = value; }
		}

		/// <summary>
		/// Gets or sets the Description value.
		/// </summary>
		public  string Description
		{
			get { return description; }
			set { description = value; }
		}

		/// <summary>
		/// Gets or sets the MediaType value.
		/// </summary>
		public  string MediaType
		{
			get { return mediaType; }
			set { mediaType = value; }
		}

		/// <summary>
		/// Gets or sets the PostType value.
		/// </summary>
		public  string PostType
		{
			get { return postType; }
			set { postType = value; }
		}

		/// <summary>
		/// Gets or sets the MediaURL value.
		/// </summary>
		public  string MediaURL
		{
			get { return mediaURL; }
			set { mediaURL = value; }
		}

		/// <summary>
		/// Gets or sets the ThumbnailURL value.
		/// </summary>
		public  string ThumbnailURL
		{
			get { return thumbnailURL; }
			set { thumbnailURL = value; }
		}

		/// <summary>
		/// Gets or sets the Duration value.
		/// </summary>
		public  int Duration
		{
			get { return duration; }
			set { duration = value; }
		}

		/// <summary>
		/// Gets or sets the DisplayOrder value.
		/// </summary>
		public  int DisplayOrder
		{
			get { return displayOrder; }
			set { displayOrder = value; }
		}

		/// <summary>
		/// Gets or sets the PublishDate value.
		/// </summary>
		public  DateTime PublishDate
		{
			get { return publishDate; }
			set { publishDate = value; }
		}

		/// <summary>
		/// Gets or sets the IsActive value.
		/// </summary>
		public  bool IsActive
		{
			get { return isActive; }
			set { isActive = value; }
		}

		/// <summary>
		/// Gets or sets the IsDeleted value.
		/// </summary>
		public  bool IsDeleted
		{
			get { return isDeleted; }
			set { isDeleted = value; }
		}

		/// <summary>
		/// Gets or sets the IsAdminPost value.
		/// </summary>
		public  bool IsAdminPost
		{
			get { return isAdminPost; }
			set { isAdminPost = value; }
		}

		/// <summary>
		/// Gets or sets the DateAdded value.
		/// </summary>
		public  DateTime DateAdded
		{
			get { return dateAdded; }
			set { dateAdded = value; }
		}

		/// <summary>
		/// Gets or sets the DateModified value.
		/// </summary>
		public  DateTime DateModified
		{
			get { return dateModified; }
			set { dateModified = value; }
		}

		/// <summary>
		/// Gets or sets the UpdatedByUser value.
		/// </summary>
		public  string UpdatedByUser
		{
			get { return updatedByUser; }
			set { updatedByUser = value; }
		}

		/// <summary>
		/// Gets or sets the SourceTable value.
		/// </summary>
		public  string SourceTable
		{
			get { return sourceTable; }
			set { sourceTable = value; }
		}

		/// <summary>
		/// Gets or sets the SourceID value.
		/// </summary>
		public  int SourceID
		{
			get { return sourceID; }
			set { sourceID = value; }
		}

		/// <summary>
		/// Gets or sets the UserName value.
		/// </summary>
		public  string UserName
		{
			get { return userName; }
			set { userName = value; }
		}

		/// <summary>
		/// Gets or sets the UserPhoto value.
		/// </summary>
		public  string UserPhoto
		{
			get { return userPhoto; }
			set { userPhoto = value; }
		}

		/// <summary>
		/// Gets or sets the FeedCategory value.
		/// </summary>
		public  string FeedCategory
		{
			get { return feedCategory; }
			set { feedCategory = value; }
		}

		/// <summary>
		/// Gets or sets the Location value.
		/// </summary>
		public  string Location
		{
			get { return location; }
			set { location = value; }
		}

		/// <summary>
		/// Gets or sets the Amount value.
		/// </summary>
		public  decimal Amount
		{
			get { return amount; }
			set { amount = value; }
		}

		/// <summary>
		/// Gets or sets the IsAutoGenerated value.
		/// </summary>
		public  bool IsAutoGenerated
		{
			get { return isAutoGenerated; }
			set { isAutoGenerated = value; }
		}

		#endregion
	}
}
